In [26]:
import pandas as pd
import numpy as np
import pprint
from os import walk
import scipy.stats as stats
import matplotlib.pyplot as plt

In [27]:
apoe = pd.read_csv('../ADNI/Data___Database/ADNIMERGE.csv',low_memory=False)
col_null = apoe.isnull().sum().tolist()
col_list = apoe.columns.tolist()
col_cnt_null = zip(col_list,col_null)
for i in col_cnt_null:
    print(i)

('RID', 0)
('COLPROT', 0)
('ORIGPROT', 0)
('PTID', 0)
('SITE', 0)
('VISCODE', 0)
('EXAMDATE', 0)
('DX_bl', 18)
('AGE', 9)
('PTGENDER', 0)
('PTEDUCAT', 0)
('PTETHCAT', 0)
('PTRACCAT', 0)
('PTMARRY', 1)
('APOE4', 288)
('FDG', 12364)
('PIB', 15834)
('AV45', 12977)
('FBB', 15542)
('ABETA', 13687)
('TAU', 13687)
('PTAU', 13688)
('CDRSB', 4542)
('ADAS11', 4830)
('ADAS13', 4928)
('ADASQ4', 4797)
('MMSE', 4788)
('RAVLT_immediate', 4914)
('RAVLT_learning', 4913)
('RAVLT_forgetting', 4945)
('RAVLT_perc_forgetting', 5019)
('LDELTOTAL', 6820)
('DIGITSCOR', 12257)
('TRABSCOR', 5241)
('FAQ', 4547)
('MOCA', 8826)
('EcogPtMem', 8516)
('EcogPtLang', 8532)
('EcogPtVisspat', 8608)
('EcogPtPlan', 8548)
('EcogPtOrgan', 8687)
('EcogPtDivatt', 8586)
('EcogPtTotal', 8525)
('EcogSPMem', 8472)
('EcogSPLang', 8466)
('EcogSPVisspat', 8641)
('EcogSPPlan', 8555)
('EcogSPOrgan', 8792)
('EcogSPDivatt', 8664)
('EcogSPTotal', 8474)
('FLDSTRENG', 8395)
('FSVERSION', 6156)
('IMAGEUID', 6156)
('Ventricles', 6747)
('Hippocampus', 7410)
('WholeBrain', 6494)
('Entorhinal', 7823)
('Fusiform', 7823)
('MidTemp', 7823)
('ICV', 6162)
('DX', 4823)
('mPACCdigit', 4791)
('mPACCtrailsB', 4785)
('EXAMDATE_bl', 0)
('CDRSB_bl', 0)
('ADAS11_bl', 35)
('ADAS13_bl', 105)
('ADASQ4_bl', 7)
('MMSE_bl', 1)
('RAVLT_immediate_bl', 41)
('RAVLT_learning_bl', 41)
('RAVLT_forgetting_bl', 43)
('RAVLT_perc_forgetting_bl', 66)
('LDELTOTAL_BL', 5)
('DIGITSCOR_bl', 8827)
('TRABSCOR_bl', 266)
('FAQ_bl', 88)
('mPACCdigit_bl', 3)
('mPACCtrailsB_bl', 3)
('FLDSTRENG_bl', 3163)
('FSVERSION_bl', 263)
('IMAGEUID_bl', 263)
('Ventricles_bl', 752)
('Hippocampus_bl', 2124)
('WholeBrain_bl', 463)
('Entorhinal_bl', 2287)
('Fusiform_bl', 2287)
('MidTemp_bl', 2287)
('ICV_bl', 264)
('MOCA_bl', 7396)
('EcogPtMem_bl', 7285)
('EcogPtLang_bl', 7291)
('EcogPtVisspat_bl', 7322)
('EcogPtPlan_bl', 7284)
('EcogPtOrgan_bl', 7463)
('EcogPtDivatt_bl', 7338)
('EcogPtTotal_bl', 7283)
('EcogSPMem_bl', 7322)
('EcogSPLang_bl', 7312)
('EcogSPVisspat_bl', 7437)
('EcogSPPlan_bl', 7373)
('EcogSPOrgan_bl', 7710)
('EcogSPDivatt_bl', 7489)
('EcogSPTotal_bl', 7321)
('ABETA_bl', 6082)
('TAU_bl', 6082)
('PTAU_bl', 6082)
('FDG_bl', 5004)
('PIB_bl', 15903)
('AV45_bl', 8411)
('FBB_bl', 15071)
('Years_bl', 0)
('Month_bl', 0)
('Month', 0)
('M', 0)
('update_stamp', 0)

In [28]:
apoe

,RID,COLPROT,ORIGPROT,PTID,SITE,VISCODE,EXAMDATE,DX_bl,AGE,PTGENDER,...,PTAU_bl,FDG_bl,PIB_bl,AV45_bl,FBB_bl,Years_bl,Month_bl,Month,M,update_stamp
0,2,ADNI1,ADNI1,011_S_0002,11,bl,8/9/2005,CN,74.3,Male,...,NaN,1.25173,NaN,NaN,NaN,0.000000,0.00000,0,0,01:40.0
1,3,ADNI1,ADNI1,011_S_0003,11,bl,12/9/2005,AD,81.3,Male,...,22.83,1.22163,NaN,NaN,NaN,0.000000,0.00000,0,0,01:40.0
2,3,ADNI1,ADNI1,011_S_0003,11,m06,13/3/2006,AD,81.3,Male,...,22.83,1.22163,NaN,NaN,NaN,0.498289,5.96721,6,6,01:40.0
3,3,ADNI1,ADNI1,011_S_0003,11,m12,12/9/2006,AD,81.3,Male,...,22.83,1.22163,NaN,NaN,NaN,0.999316,11.96720,12,12,01:40.0
4,3,ADNI1,ADNI1,011_S_0003,11,m24,12/9/2007,AD,81.3,Male,...,22.83,1.22163,NaN,NaN,NaN,1.998630,23.93440,24,24,01:40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16052,6961,ADNI3,ADNI3,027_S_6961,27,m12,28/7/2022,EMCI,61.9,Female,...,NaN,NaN,NaN,NaN,1.0205,1.092400,13.08200,12,12,58:47.0
16053,6987,ADNI3,ADNI3,021_S_6987,21,m12,28/7/2022,CN,65.5,Female,...,NaN,NaN,NaN,1.0803,NaN,0.963723,11.54100,12,12,58:47.0
16054,2182,ADNI3,ADNIGO,073_S_2182,73,m120,11/1/2021,EMCI,65.5,Male,...,19.22,1.25655,NaN,1.0705,NaN,9.902810,118.59000,120,120,59:40.0
16055,4612,ADNI3,ADNI2,009_S_4612,9,m126,27/7/2022,CN,68.4,Female,...,13.89,1.27466,NaN,1.1199,NaN,10.294300,123.27900,126,126,59:44.0
16056,6929,ADNI3,ADNI3,073_S_6929,73,m12,8/6/2022,EMCI,63.1,Female,...,NaN,NaN,NaN,NaN,1.0191,0.996578,11.93440,12,12,59:48.0

In [29]:
select_col = ['RID', 'PTID', 'COLPROT','ORIGPROT', 'VISCODE', 'EXAMDATE', 'DX_bl', 'DX', 'AGE', 'MMSE','MMSE_bl',
              'PTGENDER','PTEDUCAT','APOE4','ABETA','TAU','PTAU','ABETA_bl','TAU_bl','PTAU_bl',
              'EcogPtMem','EcogPtLang','EcogPtVisspat','EcogPtPlan','EcogPtOrgan','EcogPtDivatt',
              'EcogPtTotal','RAVLT_immediate_bl','RAVLT_learning_bl','RAVLT_forgetting_bl','RAVLT_perc_forgetting_bl',
              'RAVLT_immediate','RAVLT_learning','RAVLT_forgetting','RAVLT_perc_forgetting']
apoe = apoe[select_col]
apoe.isnull().sum()

RID                             0
PTID                            0
COLPROT                         0
ORIGPROT                        0
VISCODE                         0
EXAMDATE                        0
DX_bl                          18
DX                           4823
AGE                             9
MMSE                         4788
MMSE_bl                         1
PTGENDER                        0
PTEDUCAT                        0
APOE4                         288
ABETA                       13687
TAU                         13687
PTAU                        13688
ABETA_bl                     6082
TAU_bl                       6082
PTAU_bl                      6082
EcogPtMem                    8516
EcogPtLang                   8532
EcogPtVisspat                8608
EcogPtPlan                   8548
EcogPtOrgan                  8687
EcogPtDivatt                 8586
EcogPtTotal                  8525
RAVLT_immediate_bl             41
RAVLT_learning_bl              41
RAVLT_forgetting_bl            43
RAVLT_perc_forgetting_bl       66
RAVLT_immediate              4914
RAVLT_learning               4913
RAVLT_forgetting             4945
RAVLT_perc_forgetting        5019
dtype: int64

In [30]:
rid_dx_missing = set(apoe[apoe.DX.isnull()].RID.tolist())

In [31]:
rdm = list(rid_dx_missing)
apoe[apoe.RID == rdm[0]]

,RID,PTID,COLPROT,ORIGPROT,VISCODE,EXAMDATE,DX_bl,DX,AGE,MMSE,...,EcogPtDivatt,EcogPtTotal,RAVLT_immediate_bl,RAVLT_learning_bl,RAVLT_forgetting_bl,RAVLT_perc_forgetting_bl,RAVLT_immediate,RAVLT_learning,RAVLT_forgetting,RAVLT_perc_forgetting
0,2,011_S_0002,ADNI1,ADNI1,bl,8/9/2005,CN,CN,74.3,28.0,...,NaN,NaN,44.0,4.0,6.0,54.5455,44.0,4.0,6.0,54.5455
5105,2,011_S_0002,ADNI1,ADNI1,m06,6/3/2006,CN,CN,74.3,28.0,...,NaN,NaN,44.0,4.0,6.0,54.5455,40.0,3.0,3.0,37.5000
5106,2,011_S_0002,ADNI1,ADNI1,m36,27/8/2008,CN,CN,74.3,29.0,...,NaN,NaN,44.0,4.0,6.0,54.5455,34.0,2.0,7.0,87.5000
5107,2,011_S_0002,ADNIGO,ADNI1,m60,22/9/2010,CN,CN,74.3,28.0,...,1.50,1.25641,44.0,4.0,6.0,54.5455,37.0,5.0,4.0,40.0000
5108,2,011_S_0002,ADNIGO,ADNI1,m66,4/3/2011,CN,NaN,74.3,NaN,...,NaN,NaN,44.0,4.0,6.0,54.5455,NaN,NaN,NaN,NaN
11164,2,011_S_0002,ADNI2,ADNI1,m126,23/6/2016,CN,NaN,74.3,NaN,...,NaN,NaN,44.0,4.0,6.0,54.5455,NaN,NaN,NaN,NaN
11165,2,011_S_0002,ADNI2,ADNI1,m120,22/9/2015,CN,CN,74.3,28.0,...,1.75,1.56410,44.0,4.0,6.0,54.5455,34.0,5.0,8.0,80.0000
11166,2,011_S_0002,ADNI2,ADNI1,m108,13/10/2014,CN,NaN,74.3,28.0,...,NaN,NaN,44.0,4.0,6.0,54.5455,NaN,NaN,NaN,NaN
11167,2,011_S_0002,ADNI2,ADNI1,m102,17/3/2014,CN,NaN,74.3,NaN,...,NaN,NaN,44.0,4.0,6.0,54.5455,NaN,NaN,NaN,NaN
11168,2,011_S_0002,ADNI2,ADNI1,m96,9/9/2013,CN,CN,74.3,25.0,...,1.50,1.51282,44.0,4.0,6.0,54.5455,38.0,3.0,6.0,66.6667
11169,2,011_S_0002,ADNI2,ADNI1,m90,25/3/2013,CN,NaN,74.3,NaN,...,NaN,NaN,44.0,4.0,6.0,54.5455,NaN,NaN,NaN,NaN
11170,2,011_S_0002,ADNI2,ADNI1,m84,26/9/2012,CN,MCI,74.3,24.0,...,1.75,1.33333,44.0,4.0,6.0,54.5455,37.0,5.0,7.0,70.0000
11171,2,011_S_0002,ADNI2,ADNI1,m78,22/3/2012,CN,NaN,74.3,NaN,...,NaN,NaN,44.0,4.0,6.0,54.5455,NaN,NaN,NaN,NaN
11172,2,011_S_0002,ADNI2,ADNI1,m72,19/9/2011,CN,CN,74.3,23.0,...,2.00,1.53846,44.0,4.0,6.0,54.5455,42.0,3.0,5.0,55.5556
11233,2,011_S_0002,ADNI2,ADNI1,m132,27/9/2016,CN,MCI,74.3,24.0,...,2.00,2.23077,44.0,4.0,6.0,54.5455,37.0,3.0,10.0,100.0000
11234,2,011_S_0002,ADNI3,ADNI1,m144,18/10/2017,CN,MCI,74.3,23.0,...,2.00,1.51351,44.0,4.0,6.0,54.5455,35.0,4.0,3.0,37.5000

In [32]:
apoe[apoe.RID == rdm[0]].DX

0         CN
5105      CN
5106      CN
5107      CN
5108     NaN
11164    NaN
11165     CN
11166    NaN
11167    NaN
11168     CN
11169    NaN
11170    MCI
11171    NaN
11172     CN
11233    MCI
11234    MCI
Name: DX, dtype: object

In [40]:
rid_list = apoe.RID.unique().tolist()
diabetes_list = [2,
 7,
 15,
 21,
 25,
 26,
 35,
 42,
 60,
 77,
 87,
 112,
 127,
 156,
 176,
 192,
 197,
 212,
 219,
 232,
 239,
 271,
 273,
 280,
 294,
 321,
 337,
 339,
 342,
 369,
 397,
 486,
 488,
 500,
 506,
 545,
 571,
 594,
 618,
 633,
 669,
 675,
 686,
 696,
 702,
 704,
 715,
 761,
 762,
 779,
 790,
 826,
 836,
 854,
 922,
 941,
 942,
 943,
 945,
 972,
 976,
 1001,
 1004,
 1007,
 1019,
 1021,
 1066,
 1094,
 1095,
 1143,
 1158,
 1161,
 1167,
 1195,
 1201,
 1243,
 1244,
 1250,
 1255,
 1260,
 1271,
 1275,
 1280,
 1298,
 1343,
 1366,
 1380,
 1408,
 1419,
 1423,
 2002,
 2007,
 2028,
 2039,
 2063,
 2068,
 2087,
 2104,
 2151,
 2156,
 2157,
 2192,
 2193,
 2201,
 2210,
 2214,
 2219,
 2234,
 2243,
 2263,
 2326,
 2347,
 2376,
 2377,
 2392,
 2401,
 4004,
 4035,
 4046,
 4067,
 4077,
 4086,
 4108,
 4118,
 4128,
 4142,
 4147,
 4175,
 4192,
 4196,
 4235,
 4249,
 4271,
 4272,
 4274,
 4279,
 4280,
 4293,
 4302,
 4325,
 4332,
 4342,
 4379,
 4381,
 4382,
 4384,
 4388,
 4419,
 4421,
 4422,
 4432,
 4449,
 4453,
 4454,
 4457,
 4478,
 4481,
 4486,
 4496,
 4498,
 4509,
 4569,
 4570,
 4579,
 4600,
 4608,
 4610,
 4618,
 4622,
 4623,
 4625,
 4630,
 4660,
 4669,
 4675,
 4678,
 4679,
 4680,
 4688,
 4689,
 4697,
 4702,
 4706,
 4737,
 4740,
 4743,
 4759,
 4765,
 4798,
 4813,
 4814,
 4817,
 4844,
 4857,
 4859,
 4868,
 4878,
 4883,
 4919,
 4925,
 4938,
 4968,
 4992,
 5012,
 5015,
 5032,
 5097,
 5127,
 5130,
 5138,
 5147,
 5149,
 5164,
 5166,
 5168,
 5176,
 5186,
 5187,
 5193,
 5194,
 5195,
 5200,
 5206,
 5208,
 5243,
 5251,
 5269,
 5272,
 5276,
 5284,
 5285,
 5293,
 6001,
 6023,
 6039,
 6043,
 6048,
 6061,
 6080,
 6082,
 6086,
 6088,
 6090,
 6093,
 6094,
 6145,
 6151,
 6191,
 6204,
 6209,
 6219,
 6224,
 6244,
 6245,
 6249,
 6259,
 6266,
 6270,
 6277,
 6278,
 6281,
 6282,
 6296,
 6298,
 6302,
 6306,
 6311,
 6345,
 6357,
 6383,
 6393,
 6402,
 6410,
 6440,
 6444,
 6450,
 6463,
 6468,
 6472,
 6495,
 6497,
 6509,
 6520,
 6535,
 6541,
 6546,
 6550,
 6589,
 6591,
 6594,
 6597,
 6621,
 6624,
 6630,
 6643,
 6647,
 6669,
 6677,
 6685,
 6691,
 6694,
 6696,
 6697,
 6699,
 6702,
 6726,
 6730,
 6748,
 6751,
 6761,
 6762,
 6763,
 6764,
 6765,
 6768,
 6784,
 6795,
 6796,
 6798,
 6817,
 6822,
 6826,
 6834,
 6836,
 6842,
 6845,
 6849,
 6852,
 6860,
 6863,
 6869,
 6887,
 6904,
 6907,
 6914,
 6917,
 6936,
 6937,
 6938,
 6940,
 6947,
 6949,
 6956,
 6959,
 6961,
 6962,
 6974,
 6976,
 6991,
 6993,
 6994,
 7001,
 7007,
 7030,
 7033,
 7047,
 7062,
 7070,
 7075,
 7083,
 7087,
 7095]
for i in diabetes_list:
    if i in rid_list:
        print(i)

2
7
15
21
35
42
60
77
87
112
127
156
176
219
232
273
294
321
337
339
369
397
488
500
506
545
618
633
669
675
686
696
702
715
761
779
790
836
922
941
945
972
976
1001
1004
1007
1021
1066
1094
1095
1161
1195
1201
1243
1244
1250
1255
1260
1271
1275
1280
1343
1366
1380
1408
1419
1423
2002
2007
2063
2068
2087
2151
2193
2201
2210
2219
2234
2263
2347
2376
2392
4004
4035
4067
4077
4086
4128
4175
4192
4196
4235
4271
4272
4274
4279
4280
4293
4302
4332
4379
4381
4382
4384
4388
4419
4421
4422
4432
4449
4453
4496
4498
4579
4610
4622
4623
4625
4630
4660
4675
4678
4679
4680
4688
4689
4706
4737
4740
4743
4765
4798
4813
4814
4817
4844
4857
4859
4868
4878
4883
4919
4925
4938
4968
4992
5012
5015
5032
5097
5127
5130
5138
5147
5166
5176
5187
5193
5194
5195
5200
5206
5208
5243
5251
5269
5272
5285
6001
6039
6043
6061
6080
6082
6088
6094
6145
6151
6204
6209
6224
6244
6259
6266
6277
6278
6281
6282
6298
6306
6345
6357
6393
6402
6450
6463
6468
6472
6495
6497
6509
6535
6541
6546
6550
6589
6591
6597
6621
6624
6643
6669
6677
6691
6694
6696
6697
6699
6702
6726
6730
6748
6751
6761
6763
6764
6765
6768
6784
6796
6798
6817
6822
6834
6842
6845
6849
6852
6860
6863
6869
6887
6907
6914
6917
6940
6947
6956
6959
6961
6962
6974
6976
6991
6993
6994
7001
7007
7033
7062
7070
7083

In [39]:
apoe[(apoe.COLPROT=='ADNI3')&(apoe.ORIGPROT=='ADNI3')]

,RID,PTID,COLPROT,ORIGPROT,VISCODE,EXAMDATE,DX_bl,DX,AGE,MMSE,...,EcogPtDivatt,EcogPtTotal,RAVLT_immediate_bl,RAVLT_learning_bl,RAVLT_forgetting_bl,RAVLT_perc_forgetting_bl,RAVLT_immediate,RAVLT_learning,RAVLT_forgetting,RAVLT_perc_forgetting
11198,6024,127_S_6024,ADNI3,ADNI3,bl,28/11/2017,SMC,CN,67.4,30.0,...,2.00,1.28947,60.0,9.0,1.0,7.14286,60.0,9.0,1.0,7.14286
11199,6103,002_S_6103,ADNI3,ADNI3,bl,21/11/2017,SMC,CN,69.9,30.0,...,1.00,1.02632,59.0,9.0,1.0,7.69231,59.0,9.0,1.0,7.69231
11200,6084,005_S_6084,ADNI3,ADNI3,bl,13/11/2017,SMC,CN,78.4,30.0,...,2.00,1.68421,34.0,4.0,7.0,77.77780,34.0,4.0,7.0,77.77780
11203,6027,130_S_6027,ADNI3,ADNI3,bl,20/10/2017,SMC,CN,75.6,30.0,...,2.00,1.73684,41.0,12.0,6.0,42.85710,41.0,12.0,6.0,42.85710
11206,6118,123_S_6118,ADNI3,ADNI3,bl,28/12/2017,SMC,CN,74.7,30.0,...,2.00,1.28947,49.0,6.0,5.0,41.66670,49.0,6.0,5.0,41.66670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16050,7035,037_S_7035,ADNI3,ADNI3,bl,26/7/2022,NaN,NaN,53.5,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16051,7072,014_S_7072,ADNI3,ADNI3,bl,26/7/2022,SMC,CN,62.6,28.0,...,2.25,2.15789,40.0,9.0,6.0,50.00000,40.0,9.0,6.0,50.00000
16052,6961,027_S_6961,ADNI3,ADNI3,m12,28/7/2022,EMCI,NaN,61.9,25.0,...,3.25,2.15789,36.0,7.0,6.0,60.00000,47.0,6.0,4.0,33.33330
16053,6987,021_S_6987,ADNI3,ADNI3,m12,28/7/2022,CN,NaN,65.5,NaN,...,NaN,NaN,50.0,6.0,6.0,50.00000,NaN,NaN,NaN,NaN
16056,6929,073_S_6929,ADNI3,ADNI3,m12,8/6/2022,EMCI,CN,63.1,30.0,...,2.75,2.47368,57.0,9.0,3.0,20.00000,58.0,7.0,4.0,28.57140