In [1]:
import pandas as pd
import numpy as np
import pprint
from os import walk
import scipy.stats as stats
import matplotlib.pyplot as plt

In [2]:
neur1 = pd.read_csv('/Users/sohamdighe/Documents/SCIE90017/Data/ADNI/Neuropathology_Results/NEUROPATH_05_17_21.csv')
neur1

,RID,NPFORMMO,NPFORMDY,NPFORMYR,NPDAGE,NPDODYR,NPPMIH,NPFIX,NPFIXX,NPWBRWT,...,NPBNKE,NPBNKF,NPBNKG,NPFAUT,NPFAUT1,NPFAUT2,NPFAUT3,NPFAUT4,FORMVER,update_stamp
0,8,5,1,2018,95,2017,4.50,1,NaN,1131,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:29.0
1,42,7,24,2015,81,2014,17.70,1,NaN,1290,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:29.0
2,53,4,20,2012,86,2012,22.50,1,NaN,1240,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:29.0
3,78,8,18,2017,78,2007,16.25,1,NaN,1240,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:29.0
4,91,6,4,2020,75,2018,3.10,1,NaN,990,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,5017,10,2,2015,86,2015,20.30,1,NaN,1300,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:30.0
77,5058,2,4,2020,66,2018,2.60,1,NaN,1280,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:30.0
78,5079,11,22,2020,79,2019,22.80,1,NaN,1510,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:30.0
79,5087,7,30,2020,69,2017,27.10,1,NaN,1130,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:30.0
80,5218,11,17,2016,84,2015,11.10,1,NaN,1098,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:30.0

In [4]:
neur2 = pd.read_csv('/Users/sohamdighe/Documents/SCIE90017/Data/ADNI/Neuropathology_Results/NEUROPATH_07_06_21.csv')
neur2

,RID,NPFORMMO,NPFORMDY,NPFORMYR,NPDAGE,NPDODYR,NPPMIH,NPFIX,NPFIXX,NPWBRWT,...,NPBNKE,NPBNKF,NPBNKG,NPFAUT,NPFAUT1,NPFAUT2,NPFAUT3,NPFAUT4,FORMVER,update_stamp
0,8,5,1,2018,95,2017,4.50,1,NaN,1131,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:29.0
1,42,7,24,2015,81,2014,17.70,1,NaN,1290,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:29.0
2,53,4,20,2012,86,2012,22.50,1,NaN,1240,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:29.0
3,78,8,18,2017,78,2007,16.25,1,NaN,1240,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:29.0
4,91,6,4,2020,75,2018,3.10,1,NaN,990,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,5017,10,2,2015,86,2015,20.30,1,NaN,1300,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:30.0
76,5058,2,4,2020,66,2018,2.60,1,NaN,1280,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:30.0
77,5079,11,22,2020,79,2019,22.80,1,NaN,1510,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:30.0
78,5087,7,30,2020,69,2017,27.10,1,NaN,1130,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:30.0
79,5218,11,17,2016,84,2015,11.10,1,NaN,1098,...,0,0,0,0,NaN,NaN,NaN,NaN,10,2021-05-18 10:25:30.0

In [11]:
print([i for i in neur1.isnull().sum().tolist()])

[0, 0, 0, 0, 0, 0, 0, 0, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 81, 0, 81, 0, 81, 0, 81, 0, 0, 0, 0, 0, 81, 0, 0, 0, 0, 0, 0, 0, 74, 77, 80, 80, 74, 80, 81, 81, 74, 79, 81, 81, 74, 80, 81, 81, 0, 77, 77, 77, 0, 70, 70, 70, 70, 0, 81, 81, 81, 81, 0, 0, 0, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 0, 0, 0, 81, 81, 81, 81, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 0, 70, 0, 80, 0, 0, 0, 0, 0, 0, 0, 0, 80, 80, 81, 80, 0, 0]